config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cookies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  before_action :set_cooky, only: [:show, :edit, :update, :destroy]

  # GET /cookies
  # GET /cookies.json
  def index
    for i in 1..200
      #cookies["cookie "+i.to_s] = { value: "Guru "+i.to_s, secure: true}
    end
  end

  # GET /cookies/1
  # GET /cookies/1.json
  def show
  end

  # GET /cookies/new
  def new
    @cooky = Cookie.new
  end

  # GET /cookies/1/edit
  def edit
  end

  # POST /cookies
  # POST /cookies.json
  def create
    @cooky = Cookie.new(cooky_params)

    respond_to do |format|
      if @cooky.save
        format.html { redirect_to @cooky, notice: 'Cookie was successfully created.' }
        format.json { render :show, status: :created, location: @cooky }
      else
        format.html { render :new }
        format.json { render json: @cooky.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookies/1
  # PATCH/PUT /cookies/1.json
  def update
    respond_to do |format|
      if @cooky.update(cooky_params)
        format.html { redirect_to @cooky, notice: 'Cookie was successfully updated.' }
        format.json { render :show, status: :ok, location: @cooky }
      else
        format.html { render :edit }
        format.json { render json: @cooky.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookies/1
  # DELETE /cookies/1.json
  def destroy
    @cooky.destroy
    respond_to do |format|
      format.html { redirect_to cookies_url, notice: 'Cookie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cooky
      @cooky = Cookie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cooky_params
      params.fetch(:cooky, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/views/cookies/_form.html.erb
<%= form_for(cooky) do |f| %>
  <% if cooky.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cooky.errors.count, "error") %> prohibited this cooky from being saved:</h2>

      <ul>
      <% cooky.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cookies/edit.html.erb
<h1>Editing Cooky</h1>

<%= render 'form', cooky: @cooky %>

<%= link_to 'Show', @cooky %> |
<%= link_to 'Back', cookies_path %>

app/views/cookies/index.html.erb
<!doctype HTML>
<html>
<head>
    <title>HTML Image Map</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: helvetica;
            text-align: center;
        }
    </style>
</head>
<body>
    <h2>HTML Image Map test - click the nose of Servo Doge.</h1>
    <img src="https://pbs.twimg.com/profile_images/621055164510658560/Cj-wqR55.png" alt="" usemap="#dogeMap">
    <map id="dogeMap" name="dogeMap"><area shape="rect" coords="122,211,190,265" title="Servo Experiments" alt="Servo Experiments" href="http://coookietester.herokuapp.com" target="_self" /></map>
</body>
</html>

app/views/cookies/new.html.erb
<h1>New Cooky</h1>

<%= render 'form', cooky: @cooky %>

<%= link_to 'Back', cookies_path %>

app/views/cookies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cooky_path(@cooky) %> |
<%= link_to 'Back', cookies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CTester</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>